[meta]
name = "Arbitrary Record Loader"
author = "ar....."
version = "0.1.0"
category = "ARL"

[script]
    # These are still needed, but I'd like to warn about  that instead of just not
    # allowing things to run xdd
# dependencies = [ "NadeoServices", "MLHook", "UiNav" ]
optional_dependencies = [ "NadeoServices", "MLHook", "UiNav", "ChampionMedals", "WarriorMedals", "SBVilleCampaignChallenges", "Archivist", "BetterReplaysFolder" ]
