namespace HotkeyUI {
    const vec4 COL_ERR = vec4(1.0f, 0.30f, 0.30f, 1.0f);
    const vec4 COL_OK = vec4(0.35f, 1.0f, 0.45f, 1.0f);
    const vec4 COL_WARN = vec4(1.0f, 0.75f, 0.25f, 1.0f);

    const string THIS_PLUGIN = Meta::ExecutingPlugin().Name.ToLower();

    class Binding {
        bool enabled = true;
        string plugin;
        string mod;
        string act;
        string expr;
        string desc;
    }

    class EditorState {
        int idx = -1;
        string plugin = THIS_PLUGIN;
        string mod = "";
        string act = "";
        string expr = "";
        string desc = "";
        bool capture = false;
    }

    array<Binding@> g_Binds;
    EditorState@ g_Edit = null;
    bool g_Loaded = false;
    bool g_FilterPlugin = true;
    int g_DeleteIndex = -1;

    void EnsureLoaded() {
        if (g_Loaded) return;
        g_Loaded = true;
        LoadFile();
    }

    bool Pass(const Binding@ binding) {
        if (binding is null) return false;
        return !g_FilterPlugin || binding.plugin.ToLower() == THIS_PLUGIN;
    }

    string ConfigPath() {
        return Hotkeys::GetConfigPath();
    }

    void LoadFile() {
        g_Binds.RemoveRange(0, g_Binds.Length);

        string path = ConfigPath();
        if (!IO::FileExists(path)) return;

        IO::File file(path, IO::FileMode::Read);
        auto lines = file.ReadToEnd().Split("\n");
        file.Close();

        for (uint i = 0; i < lines.Length; i++) {
            string line = lines[i].Trim();
            if (line.Length == 0 || line.StartsWith("#")) continue;

            int eq = line.IndexOf("=");
            if (eq < 0) continue;

            string lhs = line.SubStr(0, eq).Trim();
            string rhs = line.SubStr(eq + 1).Trim();

            string desc;
            int sc = rhs.IndexOf(";");
            if (sc >= 0) {
                desc = rhs.SubStr(sc + 1).Trim();
                rhs = rhs.SubStr(0, sc).Trim();
            }

            bool enabled = true;
            if (rhs.StartsWith("!")) {
                enabled = false;
                rhs = rhs.SubStr(1).Trim();
            }

            int first = lhs.IndexOf(".");
            int last = lhs.LastIndexOf(".");
            if (first < 0 || last <= first) continue;

            Binding@ binding = Binding();
            binding.plugin = lhs.SubStr(0, first).Trim();
            binding.mod = lhs.SubStr(first + 1, last - first - 1).Trim();
            binding.act = lhs.SubStr(last + 1).Trim();
            binding.expr = FormatExpr(rhs);
            binding.desc = desc;
            binding.enabled = enabled;
            g_Binds.InsertLast(binding);
        }
    }

    void SaveFile() {
        IO::File file(ConfigPath(), IO::FileMode::Write);
        file.WriteLine("# Hotkeys.cfg - generated by ARL Hotkey Manager");
        for (uint i = 0; i < g_Binds.Length; i++) {
            auto binding = g_Binds[i];
            if (binding is null) continue;

            string line = binding.plugin + "." + binding.mod + "." + binding.act + " = ";
            if (!binding.enabled) line += "!";
            line += FormatExpr(binding.expr);
            if (binding.desc.Length > 0) line += " ; " + binding.desc;
            file.WriteLine(line);
        }
        file.Close();
        Hotkeys::ReloadBindings();
    }

    UI::InputBlocking OnKeyPress(bool, VirtualKey key) {
        if (g_Edit is null || !g_Edit.capture) return UI::InputBlocking::DoNothing;

        string token = tostring(key);
        if (g_Edit.expr.Trim().Length == 0) g_Edit.expr = token;
        else g_Edit.expr += " + " + token;
        g_Edit.expr = FormatExpr(g_Edit.expr);
        g_Edit.capture = false;
        return UI::InputBlocking::DoNothing;
    }

    string JoinTokens(const array<string>@ tokens) {
        if (tokens is null || tokens.Length == 0) return "";
        string joined;
        for (uint i = 0; i < tokens.Length; i++) {
            if (i > 0) joined += " ";
            joined += tokens[i];
        }
        return joined;
    }

    string FormatExpr(const string &in raw) {
        array<string> tokens;
        uint i = 0;
        while (i < uint(raw.Length)) {
            string ch = raw.SubStr(i, 1);
            if (ch == " " || ch == "\t") {
                i++;
                continue;
            }

            if (ch == "(" || ch == ")" || ch == "+" || ch == "|") {
                tokens.InsertLast(ch);
                i++;
                continue;
            }

            if (ch == "&" && i + 1 < uint(raw.Length) && raw.SubStr(i + 1, 1) == ">") {
                tokens.InsertLast("&>");
                i += 2;
                continue;
            }

            string word;
            while (i < uint(raw.Length)) {
                string next = raw.SubStr(i, 1);
                if (next == " " || next == "\t" || next == "(" || next == ")" || next == "+" || next == "|" || next == "&") break;
                word += next;
                i++;
            }
            if (word.Length > 0) tokens.InsertLast(word);
        }
        return JoinTokens(tokens);
    }

    string CanonKey(const string &in expr) {
        string formatted = FormatExpr(expr).ToLower();
        return formatted.Replace(" ", "");
    }

    bool IsAllowedChar(uint8 ch) {
        if (ch >= 128) return false;
        if ((ch >= 65 && ch <= 90) || (ch >= 97 && ch <= 122)) return true;
        if (ch >= 48 && ch <= 57) return true;
        if (ch == 32 || ch == 9) return true;
        if (ch == 40 || ch == 41 || ch == 43 || ch == 124 || ch == 38 || ch == 62 || ch == 95) return true;
        return false;
    }

    bool HasUnsupported(const string &in text) {
        for (uint i = 0; i < uint(text.Length); i++) {
            if (!IsAllowedChar(uint8(text[i]))) return true;
        }
        return false;
    }

    int ResolveVK(const string &in token) {
        return Hotkeys::ResolveVK(token);
    }

    int ResolveGP(const string &in token) {
        return Hotkeys::ResolveGP(token);
    }

    bool TokenIsKey(const string &in token) {
        if (ResolveVK(token) >= 0) return true;
        if (ResolveGP(token) >= 0) return true;
        int literal;
        return Text::TryParseInt(token, literal, 0);
    }

    bool TokensValid(const array<string>@ tokens, bool &out syntaxOk, bool &out keyOk) {
        syntaxOk = true;
        keyOk = true;

        if (tokens is null || tokens.Length == 0) return true;

        array<string> ops = { "+", "|", "&>" };
        string first = tokens[0];
        string last = tokens[tokens.Length - 1];

        if (ops.Find(first) >= 0 || first == ")") syntaxOk = false;
        if (ops.Find(last) >= 0 || last == "(") syntaxOk = false;

        for (uint i = 0; i < tokens.Length; i++) {
            string token = tokens[i];
            if (i > 0) {
                bool prevOp = ops.Find(tokens[i - 1]) >= 0;
                bool curOp = ops.Find(token) >= 0;
                if (prevOp && curOp) syntaxOk = false;
            }

            if (token == "+" || token == "|" || token == "&>" || token == "(" || token == ")") continue;
            if (!TokenIsKey(token)) keyOk = false;
        }

        return syntaxOk && keyOk;
    }

    array<string>@ SplitTokens(const string &in expr) {
        auto formatted = FormatExpr(expr);
        if (formatted.Length == 0) return array<string>();
        return formatted.Split(" ");
    }

    array<string>@ GetModuleIds(const string &in plugin) {
        auto keys = Hotkeys::modules.GetKeys();
        array<string>@ moduleIds = array<string>();
        string prefix = plugin.ToLower() + ".";
        for (uint i = 0; i < keys.Length; i++) {
            if (!keys[i].StartsWith(prefix)) continue;
            moduleIds.InsertLast(keys[i].SubStr(prefix.Length));
        }
        return moduleIds;
    }

    string GetModuleKey(const string &in plugin, const string &in mod) {
        return (plugin + "." + mod).ToLower();
    }

    Hotkeys::IHotkeyModule@ GetSelectedModule(EditorState@ edit) {
        if (edit is null || edit.mod.Length == 0) return null;
        Hotkeys::IHotkeyModule@ module;
        Hotkeys::modules.Get(GetModuleKey(edit.plugin, edit.mod), @module);
        return module;
    }

    void StartNewBinding() {
        @g_Edit = EditorState();
        g_Edit.plugin = THIS_PLUGIN;
        auto mods = GetModuleIds(g_Edit.plugin);
        if (mods.Length == 1) g_Edit.mod = mods[0];
    }

    void StartEditBinding(int idx) {
        if (idx < 0 || idx >= int(g_Binds.Length)) return;
        auto binding = g_Binds[idx];
        if (binding is null) return;

        @g_Edit = EditorState();
        g_Edit.idx = idx;
        g_Edit.plugin = binding.plugin.ToLower();
        g_Edit.mod = binding.mod;
        g_Edit.act = binding.act;
        g_Edit.expr = FormatExpr(binding.expr);
        g_Edit.desc = binding.desc;
    }

    bool DrawModuleActionSelectors(EditorState@ edit) {
        auto modIds = GetModuleIds(edit.plugin);
        if (modIds.Length == 0) {
            UI::TextDisabled("No hotkey modules registered yet.");
            return false;
        }

        if (edit.mod.Length == 0 && modIds.Length == 1) edit.mod = modIds[0];

        int currentModule = modIds.Find(edit.mod);
        string moduleLabel = currentModule >= 0 ? modIds[currentModule] : "<module>";
        if (UI::BeginCombo("Module", moduleLabel)) {
            for (uint i = 0; i < modIds.Length; i++) {
                bool selected = int(i) == currentModule;
                if (UI::Selectable(modIds[i], selected)) {
                    edit.mod = modIds[i];
                    edit.act = "";
                }
                if (selected) UI::SetItemDefaultFocus();
            }
            UI::EndCombo();
        }

        auto module = GetSelectedModule(edit);
        if (module is null) return false;

        auto acts = module.GetAvailableActions();
        if (edit.act.Length == 0 && acts.Length == 1) edit.act = acts[0];
        int currentAction = acts.Find(edit.act);
        string actionLabel = currentAction >= 0 ? acts[currentAction] : "<action>";
        if (UI::BeginCombo("Action", actionLabel)) {
            for (uint i = 0; i < acts.Length; i++) {
                bool selected = int(i) == currentAction;
                if (UI::Selectable(acts[i], selected)) {
                    edit.act = acts[i];
                }
                if (selected) UI::SetItemDefaultFocus();
            }
            UI::EndCombo();
        }

        string actionDesc = module.GetActionDescription(edit.act);
        if (actionDesc.Length > 0) {
            UI::TextDisabled(actionDesc);
        }
        return true;
    }

    void DrawEditor() {
        if (g_Edit is null) return;

        UI::PushStyleVar(UI::StyleVar::ItemSpacing, vec2(6, 6));
        UI::PushStyleColor(UI::Col::ChildBg, vec4(0.12f, 0.12f, 0.15f, 0.7f));
        UI::PushStyleVar(UI::StyleVar::ChildRounding, 4.0f);

        if (UI::BeginChild("ARLHotkeyEditor", vec2(0, 250), true)) {
            UI::Text((g_Edit.idx < 0 ? Icons::Plus + " New Binding" : Icons::Pencil + " Edit Binding"));
            UI::TextDisabled("Config: " + ConfigPath());
            UI::Dummy(vec2(0, 2));

            DrawModuleActionSelectors(g_Edit);

            UI::Dummy(vec2(0, 2));
            UI::AlignTextToFramePadding();
            UI::Text("Expression");
            UI::SameLine();
            if (!g_Edit.capture) {
                if (_UI::Button(Icons::KeyboardO + " Capture Key")) {
                    g_Edit.capture = true;
                }
            } else {
                UI::TextDisabled("\\$ff0press a key...\\$z");
            }
            _UI::SimpleTooltip("Appends the next pressed keyboard key token to the expression.");

            g_Edit.expr = UI::InputText("##ARLHotkeyExpr", g_Edit.expr);
            g_Edit.expr = FormatExpr(g_Edit.expr);
            UI::TextDisabled("DSL: use `+` for AND, `|` for OR, `&>` for sequence. Example: `Ctrl + Shift + L`");

            auto tokens = SplitTokens(g_Edit.expr);
            bool syntaxOk, keyOk;
            bool tokenOk = TokensValid(tokens, syntaxOk, keyOk);
            Hotkeys::Parser parser(g_Edit.expr);
            bool parseOk = parser.Parse() !is null;
            bool unsupported = HasUnsupported(g_Edit.expr);
            bool exprOk = g_Edit.expr.Trim().Length > 0 && !unsupported && tokenOk && parseOk;
            bool ready = exprOk && g_Edit.mod.Length > 0 && g_Edit.act.Length > 0;

            vec4 statusColor = UI::GetStyleColor(UI::Col::Text);
            string status = Icons::Check + " Ready";
            if (g_Edit.expr.Trim().Length == 0) {
                status = Icons::Minus + " Empty expression";
            } else if (unsupported) {
                status = Icons::Times + " Unsupported character";
                statusColor = COL_ERR;
            } else if (!syntaxOk) {
                status = Icons::Times + " Invalid syntax";
                statusColor = COL_ERR;
            } else if (!keyOk) {
                status = Icons::Times + " Unknown key token";
                statusColor = COL_ERR;
            } else if (!parseOk) {
                status = Icons::Times + " Parse error";
                statusColor = COL_ERR;
            } else {
                statusColor = COL_OK;
            }

            bool duplicate = false;
            string canon = CanonKey(g_Edit.expr);
            for (uint i = 0; i < g_Binds.Length; i++) {
                if (g_Edit.idx >= 0 && int(i) == g_Edit.idx) continue;
                auto binding = g_Binds[i];
                if (binding is null) continue;
                if (CanonKey(binding.expr) == canon) {
                    duplicate = true;
                    break;
                }
            }

            UI::PushStyleColor(UI::Col::Text, statusColor);
            UI::Text(status);
            UI::PopStyleColor();
            if (duplicate && g_Edit.expr.Trim().Length > 0) {
                UI::SameLine();
                UI::PushStyleColor(UI::Col::Text, COL_WARN);
                UI::Text(Icons::ExclamationTriangle + " Duplicate expression");
                UI::PopStyleColor();
            }

            UI::Dummy(vec2(0, 4));
            UI::BeginDisabled(!ready);
            if (_UI::Button(g_Edit.idx < 0 ? Icons::Plus + " Add Binding" : Icons::Check + " Save Changes")) {
                Hotkeys::IHotkeyModule@ module = GetSelectedModule(g_Edit);
                string desc = module is null ? "" : module.GetActionDescription(g_Edit.act);

                if (g_Edit.idx < 0) {
                    Binding@ binding = Binding();
                    binding.plugin = g_Edit.plugin;
                    binding.mod = g_Edit.mod;
                    binding.act = g_Edit.act;
                    binding.expr = FormatExpr(g_Edit.expr);
                    binding.desc = desc;
                    binding.enabled = true;
                    g_Binds.InsertLast(binding);
                } else {
                    auto binding = g_Binds[g_Edit.idx];
                    if (binding !is null) {
                        binding.plugin = g_Edit.plugin;
                        binding.mod = g_Edit.mod;
                        binding.act = g_Edit.act;
                        binding.expr = FormatExpr(g_Edit.expr);
                        binding.desc = desc;
                    }
                }

                SaveFile();
                @g_Edit = null;
            }
            UI::EndDisabled();
            UI::SameLine();
            if (_UI::Button(Icons::Times + " Cancel")) {
                @g_Edit = null;
            }
        }
        UI::EndChild();

        UI::PopStyleVar();
        UI::PopStyleColor();
        UI::PopStyleVar();
    }

    void DrawBindingTable() {
        UI::PushStyleVar(UI::StyleVar::CellPadding, vec2(6, 4));
        UI::PushStyleColor(UI::Col::TableRowBgAlt, vec4(0.14f, 0.14f, 0.17f, 1.0f));

        int flags = UI::TableFlags::RowBg | UI::TableFlags::Borders | UI::TableFlags::ScrollY;
        if (UI::BeginTable("ARLHotkeyBindings", 5, flags, vec2(0, 280))) {
            UI::TableSetupColumn("", UI::TableColumnFlags::WidthFixed, 34);
            UI::TableSetupColumn("Module", UI::TableColumnFlags::WidthFixed, 140);
            UI::TableSetupColumn("Action", UI::TableColumnFlags::WidthStretch);
            UI::TableSetupColumn("Expression", UI::TableColumnFlags::WidthStretch);
            UI::TableSetupColumn("", UI::TableColumnFlags::WidthFixed, 110);
            UI::TableHeadersRow();

            for (uint i = 0; i < g_Binds.Length; i++) {
                auto binding = g_Binds[i];
                if (!Pass(binding)) continue;

                UI::TableNextRow();

                UI::TableNextColumn();
                bool newState = UI::Checkbox("##HKEnabled_" + i, binding.enabled);
                if (newState != binding.enabled) {
                    binding.enabled = newState;
                    SaveFile();
                }

                UI::TableNextColumn();
                UI::Text(binding.mod);

                UI::TableNextColumn();
                UI::Text(binding.act);
                if (binding.desc.Length > 0) _UI::SimpleTooltip(binding.desc);

                UI::TableNextColumn();
                UI::Text(binding.expr);

                UI::TableNextColumn();
                if (_UI::Button(Icons::Pencil + "##HKEdit_" + i, vec2(32, 0))) {
                    StartEditBinding(int(i));
                }
                UI::SameLine();
                if (_UI::Button(Icons::Trash + "##HKDelete_" + i, vec2(32, 0))) {
                    g_DeleteIndex = int(i);
                    UI::OpenPopup("Delete Hotkey");
                }
            }

            UI::EndTable();
        }

        UI::PopStyleColor();
        UI::PopStyleVar();
    }

    void DrawDeletePopup() {
        if (!UI::BeginPopupModal("Delete Hotkey", UI::WindowFlags::AlwaysAutoResize)) return;

        UI::Text("Delete this hotkey binding?");
        if (g_DeleteIndex >= 0 && g_DeleteIndex < int(g_Binds.Length)) {
            auto binding = g_Binds[g_DeleteIndex];
            if (binding !is null) {
                UI::Separator();
                UI::Text("Module: " + binding.mod);
                UI::Text("Action: " + binding.act);
                UI::Text("Expr: " + binding.expr);
            }
        }
        UI::Separator();
        if (_UI::Button("Delete", vec2(80, 0))) {
            if (g_DeleteIndex >= 0 && g_DeleteIndex < int(g_Binds.Length)) {
                g_Binds.RemoveAt(g_DeleteIndex);
                SaveFile();
            }
            g_DeleteIndex = -1;
            UI::CloseCurrentPopup();
        }
        UI::SameLine();
        if (_UI::Button("Cancel", vec2(80, 0))) {
            g_DeleteIndex = -1;
            UI::CloseCurrentPopup();
        }
        UI::EndPopup();
    }

    void Render() {
        EnsureLoaded();

        UI::TextDisabled("Shared hotkey DSL and config format compatible with the PB hotkey setup.");
        UI::TextDisabled("Config file: " + ConfigPath());
        UI::Dummy(vec2(0, 4));

        if (_UI::Button(Icons::Plus + " Add Binding")) {
            StartNewBinding();
        }
        UI::SameLine();
        if (_UI::Button(Icons::Refresh + " Reload")) {
            LoadFile();
            Hotkeys::ReloadBindings();
        }
        UI::SameLine();
        g_FilterPlugin = UI::Checkbox("Show only ARL", g_FilterPlugin);

        DrawEditor();
        DrawBindingTable();
        DrawDeletePopup();
    }
}
